name: CI/CD for PetClient in Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # → Setting up the environment with JDK 11
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # → Building the .jar of the application
      - name: Build with Maven
        run: mvn clean install

      # → Uploading the artifact that we just built
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  continuous-deployment:
    runs-on: ubuntu-latest
    # → waiting for the contiuous integration job
    needs: [continuous-integration]

    environment:
      name: 'Production'

    # → Downloading the previous artifact to deploy it
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      # → Using webapps-deploy action to deploy the .jar in the azure web service app
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'petclientapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D9E34B44CE294DA1BA694EE92E33DFD8 }}
          package: '*.jar'
